/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MMKH (https://sketchfab.com/mmkh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/snowglobe-day-11-3dinktober2019-snow-08b4443a71c94647a1298346a1ea1203
Title: Snowglobe - Day 11 #3DInktober2019-Snow
*/

import { useFrame, useThree } from '@react-three/fiber'
import { MeshTransmissionMaterial, useGLTF, useTexture, Text, Billboard, Text3D } from '@react-three/drei'
import * as THREE from 'three'
import { useMemo, useRef, useLayoutEffect, useState, useEffect, memo } from 'react'
import { easing } from 'maath'
import gsap from 'gsap'
import SnowFlakes from './SnowFlakes'
import LumaWorld from './LumaWorld'

export default function SnowGlobeModel(props) {
  const { nodes, materials } = useGLTF('/snowglobe-transformed.glb')
  const footer = document.querySelector('.footer')
  const snowGlobeRef = useRef()
  const snowGlobeRef2 = useRef()
  const internalWorldRef = useRef()
  const [insideMesh, setInsideMesh] = useState(false)

  const groupRef = useRef()
  const texture = useTexture('/epic.jpg')
  const { camera } = useThree()
  const cameraPosition = camera.position
  const ray = new THREE.Ray(new THREE.Vector2(0, 0), cameraPosition)
  const raycaster = new THREE.Raycaster()

  function useGsapContext(scope) {
    const ctx = useMemo(() => gsap.context(() => {}, scope), [scope])
    return ctx
  }

  const ctx = useGsapContext(snowGlobeRef)

  useLayoutEffect(() => {
    gsap.to(camera.position, {
      z: props.inside ? 0.1 : 3,
      x: props.inside ? 0.1 : 3,
      ease: 'power3.inOut',
      duration: 1.8
    })

    return () => ctx.revert()
  }, [props.inside])

  useFrame((state, delta) => {
    checkIntersection(snowGlobeRef.current, delta)
  })

  const checkIntersection = (object, delta) => {
    raycaster.set(cameraPosition, ray.direction)

    const intersections = raycaster.intersectObject(object)

    if (intersections.length > 0) {
      setInsideMesh(false)
    } else {
      setInsideMesh(true)
    }
    easing.dampC(internalWorldRef.current.material.color, intersections.length > 0 ? 'grey' : 'white', 0.25, delta)
    easing.damp(footer.style, 'opacity', intersections.length > 0 ? '0.1' : '1', 0.25, delta)
  }

  useEffect(() => {
    if (!insideMesh) {
      snowGlobeRef2.current.visible = false
      snowGlobeRef.current.visible = false
      camera.fov = 95
      camera.updateProjectionMatrix()
    } else {
      camera.fov = 65
      camera.updateProjectionMatrix()
      snowGlobeRef2.current.visible = true
      snowGlobeRef.current.visible = true
    }
  }, [insideMesh])

  return (
    <group
      ref={groupRef}
      {...props}
      dispose={null}
    >
      <mesh
        ref={snowGlobeRef}
        castShadow
        receiveShadow
        geometry={nodes.build_scenebuild_sceneSnow_Scene_Snow_Globe___Default1_0.geometry}
      >
        <MeshTransmissionMaterial
          backsideThickness={8}
          samples={4}
          thickness={0.9}
          anisotropicBlur={1}
          ior={1.8}
          iridescence={0.5}
          iridescenceIOR={1}
          iridescenceThicknessRange={[0, 1400]}
          clearcoat={1}
          roughness={0.2}
          envMapIntensity={0.7}
          metalness={0.3}
        />
      </mesh>

      <mesh
        ref={internalWorldRef}
        position={[0, 15, 0]}
      >
        <sphereGeometry args={[12.5, 24, 24]} />
        <meshStandardMaterial
          map={texture}
          side={THREE.BackSide}
          envMapIntensity={3}
        />
      </mesh>
      <mesh
        ref={snowGlobeRef2}
        castShadow
        receiveShadow
        geometry={nodes.build_scenebuild_sceneSnow_Scene_blinn1_0.geometry}
      >
        <meshPhysicalMaterial
          metalness={0.2}
          roughness={0.2}
          color={'grey'}
          envMapIntensity={2}
        />
        <SnowFlakes count={2000} />
      </mesh>
      {!props.isMobile && <LumaWorld visible={insideMesh} />}
      <Texts />
    </group>
  )
}
useGLTF.preload('/snowglobe-transformed.glb')

function Texts() {
  return (
    <>
      <Text3D
        letterSpacing={0.06}
        size={0.3}
        font='/Inter_Bold.json'
        position={[-2.8, 3.3, 10]}
      >
        ANDERSON MANCINI
        <meshPhysicalMaterial
          metalness={0.2}
          roughness={0.2}
          color={'#a1a1a1'}
        />
      </Text3D>
      <Billboard>
        <Text
          resolution={1024}
          font='/DancingScript-VariableFont_wght.ttf'
          maxWidth={3.5}
          textAlign='center'
          position={[0, 12.9, 0]}
          fontSize='0.35'
          lineHeight={0.85}
        >
          This is the Christmas story of Ion, Juan and Anna. {'\n\n'}
        </Text>
        <Text
          resolution={1024}

          font='/DancingScript-VariableFont_wght.ttf'
          maxWidth={3.5}
          textAlign='center'
          position={[0, 11.7, 0]}
          fontSize='0.1'
          lineHeight={0.9}
        >
          On Christmas Eve, three silly elves— Ion, Juan, and Anna—found a pouch of “Magical North Pole Grass” in Santa’s workshop. They lit it with a peppermint-stick pipe near the candy cane forest, and soon they were laughing at everything.{'\n\n'}

Ion suddenly jumped up. “The gingerbread men in the bakery are alive! We have to see this.”{'\n\n'}

Juan laughed so hard he fell over. “Alive cookies? You’re crazy, but let’s do it!”{'\n\n'}

They snuck into the bakery, and Anna pointed at a tray of cookies. “Wait… are they moving?”{'\n\n'}

One little gingerbread man stood up, threw a gumdrop at Juan, and shouted, “Catch me if you can!” Chaos broke loose. Frosting flew through the air, sprinkles spilled everywhere, and the elves chased the cookies around, laughing so hard they could barely breathe.{'\n\n'}

Juan tried to catch one but slipped on some spilled syrup, landing in a pile of marshmallows. “I’m fine!” he shouted, cracking up as the others laughed at him.{'\n\n'}

Finally, the gingerbread men climbed onto a sugar-cube sleigh and rode off into the night. Anna shook her head. “Santa’s going to kill us.”{'\n\n'}

Ion grinned. “But this was totally worth it.”{'\n\n'}

Juan, covered in syrup, added, “Best Christmas ever!”
        </Text>
        
        <Text
          maxWidth={1.5}
          resolution={1024}

          textAlign='center'
          position={[0, 10.5, 0]}
          fontSize='0.08'
        >
          Anderson Mancini
        </Text>
      </Billboard>
    </>
  )
}
